- name: Configure all VMs
  hosts: all
  become: yes
  roles:
    - common
    - docker

- name: Configure SonarQube
  hosts: ops
  become: yes
  roles:
    - sonarqube

- name: Deploy frontend
  hosts: frontend
  become: yes
  roles:
    - frontend_deploy

- name: Deploy backend
  hosts: backend
  become: yes
  roles:
    - backend_deploy