all:
  children:
    frontend_vms:
      hosts:
        vm-frontend:
          ansible_host: 10.0.1.4
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/vm_key
    backend_vms:
      hosts:
        vm-backend:
          ansible_host: 10.0.2.4
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/vm_key
    sonar_vms:
      hosts:
        vm-sonar:
          ansible_host: 10.0.4.4
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/vm_key
