project: "project2"
group: "g6"
suffix: "{{ project }}-{{ group }}"
compact_suffix: "{{ project }}{{ group }}"
acr_login_server: "acr{{ compact_suffix }}.azurecr.io"
frontend_image:   "{{ acr_login_server }}/frontend:{{ image_tag | default('latest') }}"
backend_image:    "{{ acr_login_server }}/backend:{{ image_tag | default('latest') }}"
backend_port:     "8080"
frontend_port:    "80"
